# Generated by Django 5.2.7 on 2025-10-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_migration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamigration',
            name='target_model',
            field=models.CharField(choices=[('gso_inventory.InventoryItem', 'Inventory Items'), ('gso_reports.DataMigration', 'Work Accomplishment Reports'), ('gso_requests.ServiceRequest', 'Service Requests')], max_length=100),
        ),
    ]
